const fs = require('fs');
const path = require('path');

const name = process.argv[2];
if (!name) {
  console.error('Usage: node create-module.js <ModuleName>');
  process.exit(1);
}

const base = path.join(__dirname, '..', 'src', 'modules', name);
if (fs.existsSync(base)) {
  console.error(`Module folder already exists: ${base}`);
  process.exit(1);
}

fs.mkdirSync(base, { recursive: true });

const component = `import React from 'react';\nimport './${name}.css';\n\nconst ${name}: React.FC = () => {\n  return (<div className=\"${name.toLowerCase()}-module\">\n    <h2>${name} module</h2>\n  </div>);\n};\n\nexport default ${name};\n`;
fs.writeFileSync(path.join(base, `${name}.tsx`), component);

const css = `/* Styles for ${name} module */\n.${name.toLowerCase()}-module {\n  padding: 12px;\n}\n`;
fs.writeFileSync(path.join(base, `${name}.css`), css);

const readme = `# ${name} module\n\nThis module was generated by the helper.\n`;
fs.writeFileSync(path.join(base, `README.md`), readme);

console.log(`Created module: ${base}`);
